name: Deploy Webpage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (if using build tools)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies (if needed)
        run: npm install

      - name: Build and deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # You can change this to the folder where your build output is
